version: '3.9'

services:
  backend:
    build: ./backend
    environment:
      MONGO_URI: "mongodb+srv://admin:4t4JdIInKHMY5CZz@messageboard-database.mjot3.mongodb.net/messageboard?retryWrites=true&w=majority"
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
